### ISSUE TITLE
Project status on OWASP website

### ISSUE THREAD

**Issue by walterdolce** [epsylon/xsser-public#10]
Hi,

I see a new version (1.7) has been released but [on the OWASP Xsser project page](https://www.owasp.org/index.php/OWASP_XSSER) they state Xsser is an inactive project. I think the community would benefit from seeing the project is alive and thriving.

Is there any chance it could be "brought back to life" on the OWASP website?

Additionally, the current Kali Linux distribution ships with xsser 1.6. I'm not sure whether a revamp of the project status on the OWASP website would make any difference for that.

**Comment by walterdolce** [comment]
I see, didn't know that.

I guess we're sorted then and should only wait to hearing from them ;)

Will close this. Thanks!

**Comment by epsylon** [comment]
And we hope that this time Kali Linux packagers will try to implement correctly XSSer map. Much better to packate it with map on local, so no need to download it from external sources, that is a common problem for 'newbies'. I mean, try to implement geoip libs better for distribution in general...

**Comment by epsylon** [comment]
Thanks for report it :-)

**Comment by walterdolce** [comment]
> And we hope that this time Kali Linux packagers will try to implement
correctly XSSer map

Are they aware of the best way to bundle it within the distro?

**Comment by epsylon** [comment]
I don't know. We should pay attention to see how it is implemented this time and give a solution directly to tracker if is not correctly...

**Comment by walterdolce** [comment]
I agree. I can send them an email too and see how it goes..

**Comment by epsylon** [comment]
That sounds good!

**Comment by epsylon** [comment]
Actually geoip lib was updated on Kali distribution based OS (Debian):

[....]
Package: geoip-database
Version: 20160408-1
Installed-Size: 5437
Maintainer: Patrick Matthäi <pmatthaei@debian.org>
[....]
