### ISSUE TITLE
Suggested Patch - .gitignore

### ISSUE THREAD

**Issue by odinn1984** [epsylon/xsser-public#16]
Add a quick .gitignore file so we can use virtualenvs and and ignore pyc files as well.

`
From f4dc7e816f6f37c7916c43cc12bfe5c8c8f555dc Mon Sep 17 00:00:00 2001
From: Odinn <odinn@Odinns-MacBook-Pro.local>
Date: Fri, 14 Oct 2016 04:49:25 +0300
Subject: [PATCH] add .gitignore file to ignore virtualenv and .pyc files

---
 .gitignore | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 .gitignore

diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..d22d9b3
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1,3 @@
+virtualenv
+virtualenv/*
+*.pyc
-- 
2.8.4 (Apple Git-73)

`

**Comment by epsylon** [comment]
Roger!

**Comment by odinn1984** [comment]
@epsylon i've opened a PR for it if you agree to merge: https://github.com/epsylon/xsser-public/pull/17

**Comment by epsylon** [comment]
@odinn1984 Thanks for contribute with that detail... I added it for next release (for github distribution, not to main package).
