### ISSUE TITLE
Internal error getting -payloads- error

### ISSUE THREAD

**Issue by dschu-lab** [epsylon/xsser-public#2]
Hey there,

I'm trying to test my application with your tool, but I'm stuck on this error:
```
Traceback (most recent call last):
  File "/Users/..../xsser-public/xsser-public/core/main.py", line 1437, in try_running
    return func(*args)
  File "/Users/..../xsser-public/xsser-public/core/main.py", line 285, in get_payloads
    payloads_css    = core.fuzzing.vectors.vectors_css
AttributeError: 'module' object has no attribute 'vectors_css'
```
Any idea what's going wrong?

**Comment by epsylon** [comment]
Hi,

Yes I know. This was a non-complete development did for Google Summer of Code about a module to inject javascript over CSS styles. I think it was not complete, so, try to comment it on code...

If not you can try this package: http://xsser.03c8.net/xsser/xsser_1.6-1.tar.gz

I will try to fix it soon.

Thanks for your report.

**Comment by epsylon** [comment]
Ok, fixed!. https://github.com/epsylon/xsser-public/blob/master/xsser-public/core/fuzzing/vectors_css.py

**Comment by dschu-lab** [comment]
Thanks for your fast reply. After pulling the current state, I can't open XSSER:
```
from XSSer.main import xsser
ImportError: No module named XSSer.main
```

**Comment by epsylon** [comment]
Do you have a folder named: "core" or "XSSer"?. Try to clone repo again.

**Comment by dschu-lab** [comment]
No there is no folder named XSSer...
It's because I'm running on a journaled HFS+ which is not case-sensitive. Ha ha!

**Comment by epsylon** [comment]
With last commit you should have it.
Btw, I will try to update XSSer code soon. Version "1.7b - Total Swarm" is practically ready...

**Comment by dschu-lab** [comment]
Thanks!
