### ISSUE TITLE
error: [Errno 21] Is a directory: 'xsser'

### ISSUE THREAD

**Issue by marcusguttenplan** [epsylon/xsser-public#3]
hi there -

running `setup.py build` and `setup.py make` from source package on osx both throwing `error: [Errno 21] Is a directory: 'xsser'`. it created the build folder though and added my system info. same errors when run as sudo.  all dependencies installed with pip and brew and my path is good to go. not sure what the error could be caused by, but while researching i saw a few other projects were having similar problems. are there any logs that would be useful?

thank you!

**Comment by epsylon** [comment]
Hi,
On OSx there is a problem when a package is called with same name that executable.

Here you have a commit (that was undo) that fixes that problem:

https://github.com/epsylon/xsser-public/commit/93198c1dceffff6d8750409f3ebf288bb8341c3d

Is just change folder name 'XSSer' for 'core' and change lib imports on core. If you can try it manually will work. If not, I will try to advance it and push results.

Thanks for your report.

**Comment by epsylon** [comment]
I reciently push a new code supodesly fixing this error. Please, can you try it and report to me the results?.

**Comment by marcusguttenplan** [comment]
Epsylon, thank you for the quick solution. It works great.

**Comment by epsylon** [comment]
Perfect!. Thanks to you for report.
