### ISSUE TITLE
Xsser problem

### ISSUE THREAD

**Issue by behenchod** [epsylon/xsser-public#5]
i am dealing with this problem , whenever i start xsser -- gtk and put the the required website and Aim then fly, I end up with xsser getting closed after some time automatically,i guess there is a bug , i am using xsser v1.6 beta version

**Comment by epsylon** [comment]
Hi,
Can you provide more information about this error?.
Which OS are you using?
When GUI is closed, do you have any error on shell?
Thanks for your report.

**Comment by behenchod** [comment]
I am using debian(kali linux sana 2.0) and error on shell is :---> ***
Error in `/usr/bin/python': double free or corruption (fasttop):
0x00007f84a4059bd0 ***
Aborted.

while xsser is trying injections on url of a website, after 40 to 50 tries
it automatically closes with above error.

**Comment by epsylon** [comment]
It should be nice if you can paste me rest of backtrace...

**Comment by Varun416** [comment]
I am getting issue when i am running python3 xsser --gtk i am getting error 
root@kali:~/xsser# python3 xsser --gtk
Traceback (most recent call last):
  File "xsser", line 35, in <module>
    app.run()
  File "/root/xsser/core/main.py", line 2768, in run
    self.create_gtk_interface()
  File "/root/xsser/core/main.py", line 2688, in create_gtk_interface
    from core.gtkcontroller import Controller, reactor
  File "/root/xsser/core/gtkcontroller.py", line 49, in <module>
    from core.globalmap import GlobalMap
  File "/root/xsser/core/globalmap.py", line 47, in <module>
    import GeoIP
ModuleNotFoundError: No module named 'GeoIP'

**Comment by geeknik** [comment]
```
File "/root/xsser/core/globalmap.py", line 47, in 
import GeoIP
ModuleNotFoundError: No module named 'GeoIP'
```

You’re missing the `GeoIP` module and you should install it maybe with `sudo pip3 install GeoIP`.

**Comment by epsylon** [comment]
@Varun416 your question isn't related with this thread...

Please, try to follow some order for your issues as the others do...or you will be ignored on a future.. OK?

Also you can check, before to ask here and waste the time of the other, on the Internet, for possible solutions...

Or even here, trying to found similar previous reports about your topic.

https://github.com/epsylon/xsser/issues?q=is%3Aissue+is%3Aclosed

@geeknik has provided you an answer (wrong my good friend...don't confuse _GeoIP_ with _python-geoip_, we are using the second one). 

```
GeoIP (1.3.2)                            - MaxMind GeoIP Legacy Database -  Python API
python-geoip (1.2)                       - Provides GeoIP functionality for Python.
  INSTALLED: 1.2 (latest)
```

Should be nice also, if you say "thanks" after that, to the people who tries to support you with your issues...etc.

I mean, wrong in protocol, dude!!

------

**sudo python3 setup.py install** -> should auto-install all required libs

To fix GeoIP: **sudo apt-get install python3-geoip** or **python3 -m pip install python-geoip**

**Comment by epsylon** [comment]
Also, at some OS, such as Kali, ParrotOS, Ubuntu, etc.. You should install this other lib: **pygeoip**
ex: **python3 -m pip install pygeoip**

**Comment by geeknik** [comment]
@epsylon Whoops! My bad. I was at least in the ballpark. 😆

**Comment by epsylon** [comment]
hey @geeknik In fact, you were partly right... ;-)

Since we used the old GeoIP library, which depended on another one in C (libgeoip1). 

What I have done has been to modify it so that it does not depend. 

Now yes, we use pure pygeoip (sudo apt-get install python3-geoip or pip3 install pygeoip) .. 

Hehe, so thanks!

**Comment by epsylon** [comment]
@geeknik -> https://github.com/epsylon/xsser/blob/master/core/globalmap.py#L166
