### ISSUE TITLE
Does not work with Beautiful Soup 4

### ISSUE THREAD

**Issue by Eta-Meson** [epsylon/xsser-public#6]
**XSSER** is not working with the latest version of **Beautiful Soup**

**Comment by Eta-Meson** [comment]
@epsylon  Hello I created a pull request for this Issue.

**Comment by epsylon** [comment]
@Eta-Meson many thanks for that. Because I am working on a new version I will apply your request to development code so will be present on next release.

**Comment by Eta-Meson** [comment]
Thank you very much.
